// Generated by CoffeeScript 1.10.0
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var logos;
    logos = document.querySelector('.logos');
    return logos.addEventListener('click', function() {
      if (this.classList.contains('transparent')) {
        return this.classList.remove('transparent');
      } else {
        return this.classList.add('transparent');
      }
    });
  });

}).call(this);
