// Generated by CoffeeScript 1.10.0
(function() {
  jQuery(document).ready(function($) {
    var $body, $main, $moonset, $window;
    $window = $(window);
    $body = $('body');
    $moonset = $('.moonset');
    $main = $moonset.find('main');
    return $moonset.on('scroll', function(e) {
      var blueOpacity, frontOpacity, height, progress, scroll, scrollHeight;
      height = $moonset.innerHeight();
      scroll = $moonset.scrollTop();
      scrollHeight = $moonset[0].scrollHeight;
      progress = scroll * 1 / (scrollHeight - height);
      blueOpacity = .5 - progress;
      console.log(blueOpacity);
      $('.blue').css({
        opacity: blueOpacity
      });
      frontOpacity = 1 - progress;
      return $('.front').css({
        opacity: frontOpacity
      });
    });
  });

}).call(this);
